version: '3'

services:
  php:
    image: php:5.3-apache
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./web:/var/www/web
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mini-blog
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "4306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
